Repository Devs-Com/Stose, pull requests merged in 2022-12, with the labels that each got.

#61 Corrección del diseño en la vista costo de envio
  bin/src/main/resources/static/css/costo-de-envio.css
  src/main/resources/static/css/costo-de-envio.css
  src/main/resources/templates/costos-de-envio.html
Labels: bug, frontend

#82 Configuración para despliegue de la aplicación Stose de Spring Tools 4 en Apache Tomcat 9.0
  pom.xml
  src/main/java/com/example/stose/StoseApplication.java
  src/main/resources/templates/carrito-compras.html
  src/main/resources/templates/costos-de-envio.html
  src/main/resources/templates/crear_libro.html
  src/main/resources/templates/crearblog.html
  src/main/resources/templates/editar_libro.html
  src/main/resources/templates/libro-oferta.html
  src/main/resources/templates/libros.html
  src/main/resources/templates/lista-de-deseos.html
  src/main/resources/templates/nosotros.html
  src/main/resources/templates/revision-pedido.html
  src/main/resources/templates/tienda.html
Labels: mejora

#84 Login y register con firebase
  src/main/resources/static/css/detalle-libro.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/libros.css
  src/main/resources/static/css/modalesIndex.css
  src/main/resources/static/js/autentification-Admin1/app/firebase3.js
  src/main/resources/static/js/autentification-Admin1/app/log_out1.js
  src/main/resources/static/js/autentification-Admin1/app/loginCheck1.js
  src/main/resources/static/js/autentification-Admin1/app/singinFrom1.js
  src/main/resources/static/js/autentification-Admin1/main-admin1.js
  src/main/resources/static/js/autentification-firebase/app/facebookLogin.js
  src/main/resources/static/js/autentification-firebase/app/firebase2.js
  src/main/resources/static/js/autentification-firebase/app/googleLogin.js
  src/main/resources/static/js/autentification-firebase/app/log_out.js
  src/main/resources/static/js/autentification-firebase/app/loginCheck.js
  src/main/resources/static/js/autentification-firebase/app/show_mensage.js
  src/main/resources/static/js/autentification-firebase/app/signunpForm.js
  src/main/resources/static/js/autentification-firebase/app/singinFrom.js
  src/main/resources/static/js/autentification-firebase/main-registro.js
  src/main/resources/static/js/configuracion.js
  src/main/resources/static/js/modal-admin.js
  src/main/resources/static/js/modales-index.js
  src/main/resources/templates/crearblog.html
  src/main/resources/templates/index.html
  src/main/resources/templates/libros.html
Labels: mejora, buena primera tarea, frontend, backend

#79 Boletin de Suscripcion
  src/main/resources/templates/carrito-compras.html
  src/main/resources/templates/costos-de-envio.html
  src/main/resources/templates/crearblog.html
  src/main/resources/templates/detalle-libro.html
  src/main/resources/templates/index.html
  src/main/resources/templates/libro-oferta.html
  src/main/resources/templates/lista-de-deseos.html
  src/main/resources/templates/nosotros.html
  src/main/resources/templates/revision-pedido.html
  src/main/resources/templates/tienda.html
Labels: mejora, frontend

#81 Funcionalidad del carrito de compras
  src/main/java/com/example/stose/controller/CrearBlogController.java
  src/main/java/com/example/stose/controller/LibroController.java
  src/main/java/com/example/stose/controller/NosotrosController.java
  src/main/java/com/example/stose/controller/carritoComprasController.java
  src/main/java/com/example/stose/controller/costosDeEnvioController.java
  src/main/java/com/example/stose/controller/detalleLibroController.java
  src/main/java/com/example/stose/controller/indexController.java
  src/main/java/com/example/stose/controller/libroOfertaController.java
  src/main/java/com/example/stose/controller/listaDeseosController.java
  src/main/java/com/example/stose/controller/revisionPedidoController.java
  src/main/java/com/example/stose/controller/tiendaController.java
  src/main/java/com/example/stose/entity/Carrito.java
  src/main/java/com/example/stose/repositories/CarritoRepositorio.java
  src/main/java/com/example/stose/services/CarritoServicio.java
  src/main/java/com/example/stose/services/CarritoServicioImpl.java
  src/main/resources/templates/carrito-compras.html
  src/main/resources/templates/costos-de-envio.html
  src/main/resources/templates/crearblog.html
  src/main/resources/templates/detalle-libro.html
  src/main/resources/templates/index.html
  src/main/resources/templates/libro-oferta.html
  src/main/resources/templates/lista-de-deseos.html
  src/main/resources/templates/nosotros.html
  src/main/resources/templates/revision-pedido.html
  src/main/resources/templates/tienda.html
Labels: mejora, frontend, backend
